conda version 24.1.2 python 3.11.7 unloaded.
conda version 24.1.2 python 3.11.7 loaded.
/var/spool/slurm/d/job5762350/slurm_script: line 17: cd: git/st_cvdm: No such file or directory
2025-03-11 17:08:42.508076: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-11 17:08:43.134406: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-11 17:08:45.455246: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-03-11 17:08:45.455762: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-11 17:08:45.739484: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-11 17:08:46.416658: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2025-03-11 17:08:46.417904: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/N/u/cwseitz/Quartz/.conda/envs/st_cvdm/lib/python3.11/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(
2025-03-11 17:10:23.798066: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2256] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Num CPUs Available:  1
Num GPUs Available:  0
Getting data...
Creating model...
Traceback (most recent call last):
  File "/geode2/home/u020/cwseitz/Quartz/git/st-st_cvdm/mains/train.py", line 207, in <module>
    main()
  File "/geode2/home/u020/cwseitz/Quartz/git/st-st_cvdm/mains/train.py", line 81, in main
    models = instantiate_st_cvdm(
             ^^^^^^^^^^^^^^^^^
  File "/geode2/home/u020/cwseitz/Quartz/git/st_cvdm/st_cvdm/diffusion_models/joint_model.py", line 130, in instantiate_st_cvdm
    models = create_joint_model(
             ^^^^^^^^^^^^^^^^^^^
  File "/geode2/home/u020/cwseitz/Quartz/git/st_cvdm/st_cvdm/diffusion_models/joint_model.py", line 31, in create_joint_model
    sch_model = variance_model(input_shape_condition, out_channels)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/geode2/home/u020/cwseitz/Quartz/git/st_cvdm/st_cvdm/diffusion_models/variance_model.py", line 29, in variance_model
    model, _ = UNet(
               ^^^^^
  File "/geode2/home/u020/cwseitz/Quartz/git/st_cvdm/st_cvdm/architectures/unet.py", line 160, in UNet
    merge7 = Concatenate()([conv3, up7])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/N/u/cwseitz/Quartz/.conda/envs/st_cvdm/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/N/u/cwseitz/Quartz/.conda/envs/st_cvdm/lib/python3.11/site-packages/keras/src/layers/merging/concatenate.py", line 131, in build
    raise ValueError(err_msg)
ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concatenation axis. Received: input_shape=[(None, 25, 25, 128), (None, 24, 24, 128)]
